title: Installassistant Downloader
description: Software Update Services catalog URL.
github:
  repository_url: https://github.com/chris1111/Installassistant-Downloader
remote_theme: chris1111/cayman-dark
