#!/bin/sh
catalogslog="/Private/tmp/Installassistant_Downloader_Log.txt"
rm -rf $catalogslog
rm -rf $HOME/Desktop/Installassistant_Downloader_Log.txt
# Creating log file
touch $catalogslog
echo "Parse_catalogs_url! "
Sleep 3
./installassistantPKG 2>&1 | tee $catalogslog

